#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
red='\033[0;31m'

echo ""
echo ""

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Your commit message is invalid. ❌"
    echo "Please use feat, fix, chore, docs, test, style, refactor, perf, build, ci or revert" >&2
    echo ""
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,200}$"; then
    echo "Your commit message is too long. ❌" >&2
    echo "Max 200 characters allowed."
    echo ""
    exit 1
fi
